In [1]:
import tensorflow as tf
# TensorFlowでは、とにかくテンソルが必要
# 簡単にテンソルを生成できる
x = tf.ones(shape=(2, 1))
print(x)

2022-05-23 17:45:20.982666: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-05-23 17:45:21.112457: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-23 17:45:21.112477: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


2022-05-23 17:45:27.947478: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:961] could not open file to read NUMA node: /sys/bus/pci/devices/0000:34:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-05-23 17:45:27.947796: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-05-23 17:45:27.947853: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-05-23 17:45:27.947893: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-05-23 17:45:27.947954: W tensorflow/stream_executor/platform/default/dso_loader.cc:6

In [3]:
x = tf.zeros(shape=(2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [4]:
# 平均0、標準偏差1の正規分布から抽出した乱数値のテンソル
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[ 0.13528253]
 [-1.0202888 ]
 [-1.3884798 ]], shape=(3, 1), dtype=float32)


In [6]:
# 0~1の一様分布から抽出した乱数値のサンプル
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
print(x)

tf.Tensor(
[[0.36158013]
 [0.963411  ]
 [0.21457255]], shape=(3, 1), dtype=float32)


In [7]:
# TensoeFlowで変更可能な「変数」(TensoeFlowで生成したテンソルには直接代入ができない)
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.0451413],
       [-0.5259692],
       [ 2.7705326]], dtype=float32)>


In [9]:
# 変数にはassignで代入可能
v.assign(tf.ones((3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>


In [10]:
# 要素の一部も変更可能
v[0, 0].assign(3.)
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>


In [12]:
# += みたいな
v.assign_add(tf.ones((3, 1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>
